### ISSUE TITLE
Zenodo metadata seems wrong

### ISSUE THREAD

**Issue by duetosymmetry** [moble/scri#75]
Looking at the [Zenodo version history](https://zenodo.org/search?page=1&size=20&q=conceptrecid:%224041971%22&sort=-version&all_versions=True), the "publication date" is set to March 2, 2022, for many versions that were uploaded since that time. The authors metadata field also does not seem to be updating. @keefemitman added code that is in the latest released version, but does not appear in the authors list there (and thus also the automatically-generated bibtex entry).

**Comment by moble** [comment]
Yeah, I guess Zenodo gets its info from CITATION.cff, which has the same outdated info.  I'll try to automatically update the version and date in the github action.  The authors will still need to be added manually.  Looks like Vijay, Mark, and Keefe have all contributed since that was updated; I'll have to just try to remember to get people to add themselves in the future.
